apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: kngn2jv9t-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/kngn2jv9t-java-quarkus-gitops